# Army.create!(name: 'abyssal_dwarfs')
# Army.create!(name: 'abyssals')
# Army.create!(name: 'basilea')
# Army.create!(name: 'brotherhood')
# Army.create!(name: 'dwarfs')
# Army.create!(name: 'elves')
# Army.create!(name: 'empire_of_dust')
# Army.create!(name: 'forces_of_nature')
# Army.create!(name: 'goblins')
# Army.create!(name: 'herd')
# Army.create!(name: 'kin')
# Army.create!(name: 'kingdoms_of_men')
# Army.create!(name: 'league_of_rhordia')
# Army.create!(name: 'night-stalkers')
# Army.create!(name: 'ogres')
# Army.create!(name: 'orcs')
# Army.create!(name: 'ratkin')
# Army.create!(name: 'salamanders')
# Army.create!(name: 'trident_realm')
# Army.create!(name: 'undead')
# Army.create!(name: 'varangur')

Unit.create!(name: '', army: Army.find_by_name(''))
