Army.create!(name: 'Abyssal Dwarfs')
Army.create!(name: 'The Brotherhood')
Army.create!(name: 'Dwarfs')
Army.create!(name: 'Elves')
Army.create!(name: 'Empire of Dust')
Army.create!(name: 'Forces of the Abyss')
Army.create!(name: 'Forces of Basilea')
Army.create!(name: 'Forces of Nature')
Army.create!(name: 'Goblins')
Army.create!(name: 'The Herd')
Army.create!(name: 'Kin')
Army.create!(name: 'Kingdoms of Men')
Army.create!(name: 'League of Rhordia')
Army.create!(name: 'Night-stalkers')
Army.create!(name: 'Ogres')
Army.create!(name: 'Orcs')
Army.create!(name: 'Ratkin')
Army.create!(name: 'Salamanders')
Army.create!(name: 'Trident Realm')
Army.create!(name: 'Undead')
Army.create!(name: 'Varangur')

Unit.create!(name: 'Blacksoul troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Blacksoul regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Blacksoul horde', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Berserkers troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Berserkers regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Immortal Guard troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Immortal Guard regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Decimator troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Decimator regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Decimator horde', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slave Orc troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slave Orc regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slave Orc horde', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Gargoyle troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Lesser Obsidian Golem regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Lesser Obsidian Golem horde', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slave Orc Gore Rider troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slave Orc Gore Rider regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Halfbreed troop', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Halfbreed regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Grotesque regiment', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Grotesque horde', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: "G'rog Mortar", army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Dragon Fire-team', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Katsuchan Rocket Launcher', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Angkor Heavy Mortar', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Overmaster', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Overmaster on Great Abyssal Dragon', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Slavedriver', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Halfbreed Champion', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Abyssal Grotesque Champion', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Iron-caster', army: Army.find_by_name('Abyssal Dwarfs'))
Unit.create!(name: 'Supreme Iron-caster on Great Winged Halfbreed', army: Army.find_by_name('Abyssal Dwarfs'))

Unit.create!(name: 'Villein Plowshare regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Plowshare horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Plowshare legion', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Spearmen troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Spearmen regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Spearmen horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Bowmen troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Bowmen regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Bowmen horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Brotherhood troop on foot', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Brotherhood regiment on foot', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Martyr troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Martyr regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Martyr horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Water Elemental regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Water Elemental horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Brotherhood regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Brotherhood horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Abyssal Hunt troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Abyssal Hunt regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Initiate regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Initiate horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of Redemption troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of Redemption regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Reconnoiterer troop', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Reconnoiterer regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Forsaken regiment', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Order of the Forsaken horde', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Siege Artillery', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Villein Ballista', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Greater Water Elemental', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Forsaken Beast', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Exemplar of the Brotherhood', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Exemplar Redeemer', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Devoted', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Exemplar Forsaker', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Exemplar Hunter', army: Army.find_by_name('The Brotherhood'))
Unit.create!(name: 'Exemplar Adjutant', army: Army.find_by_name('The Brotherhood'))

Unit.create!(name: 'Berserker troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Berserker regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Bulwarker troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Bulwarker regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Bulwarker horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironclad troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironclad regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironclad horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironguard troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironguard regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Crossbow troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Crossbow regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Crossbow horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Rifle troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Rifle regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironwatch Rifle horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ranger troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ranger regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Sharpshooter troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Shieldbreaker troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Shieldbreaker regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Shieldbreaker horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Earth Elemental regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Earth Elemental horde', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Berserker Brock Rider troop', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Berserker Brock Rider regiment', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Flame Belcher', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironbelcher Cannon', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ironbelcher Organ Gun', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Jarrun Bombard', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Army Standard Bearer', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Berserker Lord', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Dwarf King', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Ranger Captain', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Stone Priest', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Warsmith', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Dwarf King on Large Beast', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Battle Driller', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Greater Earth Elemental', army: Army.find_by_name('Dwarfs'))
Unit.create!(name: 'Steel Behemoth', army: Army.find_by_name('Dwarfs'))

Unit.create!(name: 'Kindred Archer troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Archer regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Archer horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Palace Guard troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Palace Guard regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Gladestalker troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Gladestalker regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Therennian Sea Guard regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Therennian Sea Guard horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Tallspear troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Tallspear regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Kindred Tallspear horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Hunter of the Wild troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Hunter of the Wild regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Forest Shambler regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Forest Shambler horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Silverbreeze Cavalry troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Stormwind Cavalry troop', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Stormwind Cavalry regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Drakon Rider regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Drakon Rider horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'War Chariot regiment', army: Army.find_by_name('Elves'))
Unit.create!(name: 'War Chariot horde', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Bolt Thrower', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Dragon Breath', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Army Standard Bearer', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Elven Mage', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Noble War Chariot', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Elven King', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Elven Prince', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Forest Warden', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Dragon Kindred Lord', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Master Hunter', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Drakon Rider Lord', army: Army.find_by_name('Elves'))
Unit.create!(name: 'Tree Herder', army: Army.find_by_name('Elves'))
Unit.create!(name: 'The Green Lady', army: Army.find_by_name('Elves'))

Unit.create!(name: 'Skeleton Warrior troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Warrior regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Warrior horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Spearmen troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Spearmen regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Spearmen horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Archer troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Archer regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Archer horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Crossbowmen troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Crossbowmen regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Crossbowmen horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Mummy troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Mummy regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Enslaved Guardian regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Enslaved Guardian horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Enslaved Guardian Archer regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Enslaved Guardian Archer horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Swarm regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Swarm horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Scavenger regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Scavenger horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Cavalry troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Cavalry regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Archer Cavalry troop', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Skeleton Archer Cavalry regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Chariot regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Chariot horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Worm Rider regiment', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Worm Rider horde', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Monolith', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Balefire Catapult', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Soul Snare', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Bone Dragon', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Scorpion Husk', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Bone Giant', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Reanimated Behemoth', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Champion', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Revenant Champion on Worm', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Ahmunite Pharoah', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Ahmunite Pharoah on Royal Chariot', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Cursed High Priest', army: Army.find_by_name('Empire of Dust'))
Unit.create!(name: 'Undead Army Standard Bearer', army: Army.find_by_name('Empire of Dust'))

Unit.create!(name: 'Flamebearer troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Flamebearer regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Fleshling troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Fleshling regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Fleshling horde', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Gargoyle troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Larvae horde', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Larve legion', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Lower Abyssal troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Lower Abyssal regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Lower Abyssal legion', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Succubi troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Succubi regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Guard troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Guard regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Imp regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Imp horde', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Moloch regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Moloch horde', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Tortured Soul regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Tortured Soul horde', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Horsemen troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Horsemen regiment', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Hellhound troop', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Champion', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Harbringer', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Efreet', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Abyssal Temptress', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'The Lord of Lies', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'The Well of Souls', army: Army.find_by_name('Forces of the Abyss'))
Unit.create!(name: 'Archfiend of the Abyss', army: Army.find_by_name('Forces of the Abyss'))

Unit.create!(name: 'Crossbowmen troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Crossbowmen regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Crossbowmen horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Spear troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Spear regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Spear horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Sword troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Sword regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Men-at-arms Sword horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Paladin Foot Guard troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Paladin Foot Guard regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Pentient Mob troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Pentient Mob regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Pentient Mob horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Infantry troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Infantry regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Infantry horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Elohi regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Elohi horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Paladin Knight troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Paladin Knight regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Paladin Knight horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Panther Lancer troop', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Panther Lancer regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Panther Chariot regiment', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Sisterhood Panther Chariot horde', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Heavy Arbalest', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Abbess on Panther Chariot', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Abbess', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Bearer of the Holy Icon', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Dictator', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'High Paladin on Dragon', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'High Paladin on Griffin', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'High Paladin', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Priest', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Ur-Elohi', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'War Wizard', army: Army.find_by_name('Forces of Basilea'))
Unit.create!(name: 'Phoenix', army: Army.find_by_name('Forces of Basilea'))

Unit.create!(name: 'Naiad Heartpiercer troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Heartpiercer regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Ensnarer troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Ensnarer regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Ensnarer horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Salamander troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Salamander regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Salamander horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Hunter of the Wild troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Hunter of the Wild regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Elemental regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Elemental horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Forest Shambler regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Forest Shambler horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Centaur Bray-hunter troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Centaur Bray-hunter regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Centaur Bray-strider troop', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Centaur Bray-strider regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Sylph Talonrider regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Sylph Talonrider horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Wormrider regiment', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Wormrider horde', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Centaur Chief', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Druid', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Naiad Stalker', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Tree Herder', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Winged Unicorn', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Salamander Veteran', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Forest Warden', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Pegasus', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Unicorn', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'The Green Lady', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Greater Elemental', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Hydra', army: Army.find_by_name('Forces of Nature'))
Unit.create!(name: 'Beast of Nature', army: Army.find_by_name('Forces of Nature'))

Unit.create!(name: 'Sharpstick regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Sharpstick horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Sharpstick legion', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Rabble regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Rabble horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Rabble legion', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Spitter regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Spitter horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Troll regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Troll horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Mawbeast Pack troop', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Mawbeast Pack regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Rider troop', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Rider regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Rider horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Rider Sniff troop', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Rider Sniff regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Chariot regiment', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Fleabag Chariot horde', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Sharpstick Thrower', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'War Trombone', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Big Rocks Thrower', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'King', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'King on Chariot', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Flaggit', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Biggit', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Wiz', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Troll Bruiser', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Mincer', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Giant', army: Army.find_by_name('Goblins'))
Unit.create!(name: 'Slasher', army: Army.find_by_name('Goblins'))

Unit.create!(name: 'Tribal Warrior troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Warrior regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Warrior horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Spirit Walker troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Spirit Walker regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Spirit Walker horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Longhorn troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Longhorn regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Spear troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Spear regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Spear horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Hunter troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Hunter regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Harpy troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Guardian Brute regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Guardian Brute horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Lycan regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Lycan horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Centaur Longmane troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Centaur Longmane regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Centaur Bray-hunter troop', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Centaur Bray-hunter regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Beast Pack', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Giant Eagle regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Giant Eagle horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Chariot regiment', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Chariot horde', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Stampede', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Great Totem', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Chimera', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Brutox', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tracker', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Great Chieftan', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Great Chieftan on Chariot', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Centaur Chief', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Shaman', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Tribal Totem Bearer', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Lycan Alpha', army: Army.find_by_name('The Herd'))
Unit.create!(name: 'Guardian Champion', army: Army.find_by_name('The Herd'))

Unit.create!(name: 'Spearmen troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Spearmen regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Spearmen horde', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Crossbowmen troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Crossbowmen regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Crossbowmen horde', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Buccaneer troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Buccaneer regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Shadow troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Shadow regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Reaper Guard troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Reaper Guard regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Blade Dancer troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Blade Dancer regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Gargoyle troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Lower Abyssal troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Lower Abyssal regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Lower Abyssal horde', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Knight troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Knight regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Heralds of Woe troop', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Abyssal Rider regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Abyssal Rider horde', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Darkscythe Chariot regiment', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Darkscythe Chariot horde', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Bolt Thrower', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dragon Breath', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Hydra', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Archfiend of the Abyss', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Lord', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Lord on Black Pegasus', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Lord on Black Dragon', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Avenger', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Dark Avenger on Abyssal Mount', army: Army.find_by_name('Kin'))
Unit.create!(name: 'High Priestess of the Abyss', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Army Standard Bearer', army: Army.find_by_name('Kin'))
Unit.create!(name: 'Assassin', army: Army.find_by_name('Kin'))

Unit.create!(name: 'Shield Wall troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Shield Wall regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Shield Wall horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Foot Guard troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Foot Guard regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Foot Guard horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Pike Block regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Pike Block horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Heavy Pike Block regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Heavy Pike Block horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Spear Phalanx troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Spear Phalanx regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Spear Phalanx horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Pole-arms Block troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Pole-arms Block regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Pole-arms Block horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Militia Mob troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Militia Mob regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Militia Mob horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Militia Mob legion', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Berserker troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Berserker regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Berserker horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Bowmen troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Bowmen regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Bowmen horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Crossbowmen troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Crossbowmen regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Crossbowmen horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Arquebusier troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Arquebusier regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Arquebusier horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Knight troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Knight regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Knight horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Mounted Scout troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Mounted Sergent troop', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Mounted Sergent regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Charioteer regiment', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Charioteer horde', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Cannon', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Siege Artillery', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Ballista', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'General', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'General on Winged Beast', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Hero', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Army Standard Bearer', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Wizard', army: Army.find_by_name('Kingdoms of Men'))
Unit.create!(name: 'Beast of War', army: Army.find_by_name('Kingdoms of Men'))

Unit.create!(name: 'House Guard troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'House Guard regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'City Spear Militia troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'City Spear Militia regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'City Spear Militia horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Brave regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Brave horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Spearling regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Spearling horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Scout troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Archer regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Archer horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Crossbow Block troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Crossbow Block regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Musket Block troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Musket Block regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Dogs of War regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Dogs of War horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Household Knight troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Household Knight regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Ranger Cavalry troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Knight troop', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Knight regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Honor Guard regiment', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Honor Guard horde', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Volley Gun', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Howitzer', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Iron Beast', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Battle Shrine', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Duke', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Duke on Winged Aralez', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Duke on Ancient Winged Aralez', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Wizard', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Wizard with Winged Aralez', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Master Sergent', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Master Engineer', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Sorceror', army: Army.find_by_name('League of Rhordia'))
Unit.create!(name: 'Halfling Army Standard Bearer', army: Army.find_by_name('League of Rhordia'))

Unit.create!(name: 'Specter troop', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Specter regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Blood Worm regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Blood Worm horde', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Blood Worm legion', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Reaper troop', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Reaper regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Doppelganger regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Scarecrow regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Scarecrow horde', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Scarecrow legion', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Phantom troop', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Phantom regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Needle-fang regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Needle-fang horde', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Butcher regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Butcher horde', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Shadowhound troop', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Shadowhound regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Nightmare regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Fiend regiment', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Fiend horde', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Mind-screech', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Shadow Hulk', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Planar Apparition', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Terror', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Screamer', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Portal of Despair', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Horror', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Shade', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Banshee', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Void Lurker', army: Army.find_by_name('Night-stalkers'))
Unit.create!(name: 'Dread-fiend', army: Army.find_by_name('Night-stalkers'))

Unit.create!(name: 'Red Goblin regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Red Goblin horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Warrior regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Warrior horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Warrior legion', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Berserker Brave regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Berserker Brave horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Siege Breaker regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Siege Breaker horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Hunter regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Hunter horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Shooter regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Shooter horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Boomer regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Boomer horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Red Goblin Scout troop', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Red Goblin Scout regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Chariot regiment', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Chariot horde', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Warlord', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Captain', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Army Standard', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Warlock', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Boomer Sergent', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Siege Master', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Red Goblin Biggit', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Red Goblin Blaster', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Mammoth', army: Army.find_by_name('Ogres'))
Unit.create!(name: 'Giant', army: Army.find_by_name('Ogres'))

Unit.create!(name: 'Ax troop', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Ax regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Ax horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Morax troop', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Morax regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Greatax troop', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Greatax regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Greatax horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Skulk troop', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Orcling regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Orcling horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Troll regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Troll horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Gore Rider troop', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Gore Rider regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Gore Chariot regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Gore Chariot horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Fight Wagon regiment', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Fight Wagon horde', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Krudger', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Krudger on Slasher', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Krudger on Gore Chariot', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Flagger', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Godspeaker', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Troll Bruiser', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'Giant', army: Army.find_by_name('Orcs'))
Unit.create!(name: 'War Drum', army: Army.find_by_name('Orcs'))

Unit.create!(name: 'Tunnel Slave regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Tunnel Slave horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Tunnel Slave legion', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Warrior regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Warrior horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Spear Warrior regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Spear Warrior horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Shock Troop troop', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Shock Troop regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Shock Troop horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Blight regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Blight horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Clawshots troop', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Scurriers troop', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Brute regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Brute horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Vermintide regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Vermintide horde', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Hackpaw troop', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Hackpaw regiment', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Weapon Team', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Shredder', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Artillery', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Mutant Rat-fiend', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Death Engine', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Blight Lord', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Enforcer', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'War Chief', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Warlock', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Assassin', army: Army.find_by_name('Ratkin'))
Unit.create!(name: 'Swarm Crier', army: Army.find_by_name('Ratkin'))

Unit.create!(name: 'Salamander Prime troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Salamander Prime regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Salamander Prime horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Salamander Unblooded troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Salamander Unblooded regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Salamander Unblooded horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ancient troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ancient regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Corsair troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ceremonial Guard troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ceremonial Guard regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Warrior troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Warrior regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Warrior horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Hunter troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Fire Elemental regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Fire Elemental horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Tyrant regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Tyrant horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ember Sprite regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ember Sprite horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Kaisenor Lancer troop', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Kaisenor Lancer regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Skyraider regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Skyraider horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ancient-on-Rhinosaur regiment', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ancient-on-Rhinosaur horde', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Komodon', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Greater Fire Elemental', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Lekelidon', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Fire Drake', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ankylodon Battle Platform', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Clan Lord', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Herald', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Mage-Priest', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Battle Captain', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Battle Captain on Rhinosaur', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Clan Lord on Fire Drake', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Clutch Warden', army: Army.find_by_name('Salamanders'))
Unit.create!(name: 'Ghekkotah Skylord', army: Army.find_by_name('Salamanders'))

Unit.create!(name: 'Naiad Ensnarer troop', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Ensnarer regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Ensnarer horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Thuul troop', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Thuul regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Placoderm regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Placederm horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Nokken troop', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Nokken regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Heartpiercer troop', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Heartpiercer regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Riverguard troop', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Riverguard regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Water Elemental regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Water Elemental horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Depth Horror regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Depth Horror horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Gigas regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Gigas horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Tidal Swarm regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Tidal Swarm horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Wyrmrider regiment', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Wyrmrider horde', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: "Leviathan's Bane", army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Greater Water Elemental', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Kraken', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Knucker', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Coral Giant', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Envoy', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Riverguard Captain', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Thuul Mythican', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Placederm Defender', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Depth Horror Eternal', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Naiad Wyrmrider Centurion', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Siren', army: Army.find_by_name('Trident Realm'))
Unit.create!(name: 'Trident King', army: Army.find_by_name('Trident Realm'))

Unit.create!(name: 'Skeleton Warrior troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Warrior regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Warrior horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Spearmen troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Spearmen regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Spearmen horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Archer troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Archer regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Skeleton Archer horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Ghoul troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Ghoul regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Ghoul horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Soul Reaver Infantry troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Soul Reaver Infantry regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Wraith troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Wraith regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Mummy troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Mummy regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Zombie regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Zombie horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Zombie legion', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Zombie Troll regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Zombie Troll horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Werewolf regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Werewolf horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Wight regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Wight horde', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Soul Reaver Cavalry troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Soul Reaver Cavalry regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant Cavalry troop', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant Cavalry regiment', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Balefire Catapult', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant King', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Revenant King on Undead Wyrm', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Undead Army Standard Bearer', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Cursed Pharoah', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Vampire Lord', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Vampire on Undead Pegasus', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Vampire on Undead Dragon', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Liche King', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Necromancer', army: Army.find_by_name('Undead'))
Unit.create!(name: 'Lykanis', army: Army.find_by_name('Undead'))

Unit.create!(name: 'Warband troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Warband regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Warband horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Thrall regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Thrall horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Thrall legion', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Night Raider troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Bloodsworn troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Bloodsworn regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Bloodsworn horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Sons of Korgaan troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Sons of Korgaan regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Reaver troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Reaver regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Cave Troll regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Cave Troll horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Fallen regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Fallen horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Tundra Wolf troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Mounted Sons of Korgaan troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Mounted Sons of Korgaan regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Horse Raider troop', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Horse Raider regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Direfang Rider regiment', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Direfang Rider horde', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Devourer', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Cavern Dweller', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Jabberwock', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Magus Conclave', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Cursed Son', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Magus', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Chieftan', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Chieftan on Direfang', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'King on Chimera', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Skald', army: Army.find_by_name('Varangur'))
Unit.create!(name: 'Cave Troll King', army: Army.find_by_name('Varangur'))
